name: On Push

on:
  push:

  workflow_dispatch:


jobs:
  build_all:
    runs-on: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v4
     - uses: ssciwr/doxygen-install@v1
     - uses: lukka/get-cmake@latest
     - uses: lukka/run-cmake@v10
       with:
         workflowPreset: 'default'
      